### ISSUE TITLE
chore(deps): upgrade "Avalonia" dependencies to 11.0.0

### ISSUE THREAD

**Issue by BinToss** [jinek/Consolonia#105]
[Breaking Changes (0.10->11.0)](https://github.com/AvaloniaUI/Avalonia/wiki/Breaking-Changes#010--110)

Avalonia 11.0.0 Release Candidate 1.1 was released on May 31st.

**Comment by jinek** [comment]
I've tried 11.0.5, there are big breaking changes there. 
For example some interfaces are restricted form implementation:

> Interface member 'void Avalonia.Platform.IGeometryImpl.(This interface or abstract class is -not- implementable by user code !)()' is not implemented Interface member 'void Avalonia.Platform.ITransformedGeometryImpl.(This interface or abstract class is -not- implementable by user code !)()' is not implemented

**Comment by maxkatz6** [comment]
Since Consolonia implements a custom backend, it makes sense to enable private apis in the csproj:
```xml
<AvaloniaAccessUnstablePrivateApis>true</AvaloniaAccessUnstablePrivateApis>
```

**Comment by tomlm** [comment]
I would love to help with this port. Is there a branch?

**Comment by jinek** [comment]
@tomlm I have tried to upgrade to 11.0.9, just tried to introduce required members etc. Pushed the branch here https://github.com/jinek/Consolonia/tree/105-choredeps-upgrade-avalonia-dependencies-to-1100
Let me know if you started to work on this, please. Otherwise I will work within this branch.
My branch has many compilation errors, probably need to address this at first. The abstraction changed more than I thought.

**Comment by jinek** [comment]
I have brought it to the point where it draws something. From now what's left is we need new control templates (old does not work well). Primitives drawing seems broken a bit, text formatting does not work well etc. 
At the screenshot there is an example old Consolonia vs new Consolonia.
![Screenshot from 2024-05-01 22-19-09](https://github.com/jinek/Consolonia/assets/10516222/39601015-025a-4d5e-b717-86b3831f502f)
DataGrid is broken itself thus manual navigation in the gallery is not possible. It should be run with an argument - name of the name of the case in gallery:
![image](https://github.com/jinek/Consolonia/assets/10516222/bb3f1d2e-7ff2-4cf4-8f68-2b2d0d87f147)

**Comment by maxkatz6** [comment]
For keyboard navigation you might consider using `XYFocus` class APIs that is available in 11.1.
It was primarily implemented for TVs with only arrow keys as a navigation, but might be applied here too.
 https://github.com/AvaloniaUI/Avalonia/pull/13947

**Comment by jinek** [comment]
> For keyboard navigation you might consider using `XYFocus` class APIs that is available in 11.1. It was primarily implemented for TVs with only arrow keys as a navigation, but might be applied here too. https://docs.avaloniaui.net/docs/concepts/input/focus#directional-focus-navigation- [AvaloniaUI/Avalonia#13947](https://github.com/AvaloniaUI/Avalonia/pull/13947)

Then either in this task we need to replace Consolonia XY navigation https://github.com/jinek/Consolonia/blob/773b1e6669e77324cbc9bb89b3c1fb7bd47f9526/src/Consolonia.Core/Infrastructure/ArrowsAndKeyboardNavigationHandler.cs or we can create a separate one.
But still, currently even TAB navigation does not work, needs investigation.

**Comment by jinek** [comment]
I'm currently stuck with this version: https://github.com/jinek/Consolonia/tree/105-choredeps-upgrade-avalonia-dependencies-to-1100

Initially, everything renders correctly:
![Screenshot from 2024-05-03 21-33-32](https://github.com/jinek/Consolonia/assets/10516222/87ca96a6-2f3b-4223-81da-7027bfd456de)
However, after clicking a button, only that button and its parent elements are rendered, while the rest of the interface disappears:
![Screenshot from 2024-05-03 21-33-48](https://github.com/jinek/Consolonia/assets/10516222/7dcb84da-4351-48fc-af0d-f0dd2c4f10d0)
Resizing the window triggers a complete redraw of the entire screen and everything rendered fine.
First, I thought implementing layers correctly would resolve the problem, but it turned out to be irrelevant.

**Comment by tomlm** [comment]
> @tomlm I have tried to upgrade to 11.0.9, just tried to introduce required members etc. Pushed the branch here https://github.com/jinek/Consolonia/tree/105-choredeps-upgrade-avalonia-dependencies-to-1100 Let me know if you started to work on this, please. Otherwise I will work within this branch. My branch has many compilation errors, probably need to address this at first. The abstraction changed more than I thought.
I have gotten caught up with summer fun and completely not started this (not in any meaningful way). Sorry!

**Comment by jinek** [comment]
I've finished fixing major issues, now some controls either don't work properly or does not render properly. It needs template/styling update and may be some extension of them:

* DataGrid
1) No header bottom border (line)
2) No alternate rows
3) Items can not be selected by clicking on the row outside of text

* ComboBox
1) DropDown - overflow of the bottom border
2) Array is not rendered as several elements anymore (3rd ComboBox in gallery)

* Calendar
1) Does not work at all

* Calendar Picker
1) Shift+Tab does not bring focus back to previous element

* ListBox
1) Same as DataGrid: Items can not be selected by clicking on the row outside of text
2) Check what "Toggle" is supposed to do
3) Check what is "Always selected"

* TextBox
1) CTRL+RIGHT/LEFT does not do anything
2) Center/right aligned text: cursor is shifted one character left
3) Wrapped text - wrong behavior when text line hits the right end of textbox

* Dialog
1) Show dialog does not work

* Menu
1) Separator is probably not rendered

* ProgressBar 
1) Undetermined progress bar does not move the position

Working branch is here: https://github.com/jinek/Consolonia/tree/105-choredeps-upgrade-avalonia-dependencies-to-1100

**Comment by jinek** [comment]
I have created the pull request, now it's need a cleanup, quality checks etc
https://github.com/jinek/Consolonia/actions/runs/11420348010/job/31775946159?pr=119
and
https://github.com/jinek/Consolonia/actions/runs/11420348011/job/31775950380?pr=119
