### ISSUE TITLE
Migrate to ControlTheme

### ISSUE THREAD

**Issue by jinek** [jinek/Consolonia#106]
Example here: https://github.com/AvaloniaUI/Avalonia/blob/master/src/Avalonia.Themes.Simple/Controls/Button.xaml

**Comment by tomlm** [comment]
Instructions I came across
https://github.com/AvaloniaUI/Avalonia/wiki/Porting-to-Control-Themes

**Comment by tomlm** [comment]
I have started a branch tomlm/controlTheme

It has applied all of the changes from above, but I don't understand how they get applied. 

@jinek perhaps you can find this useful?

**Comment by jinek** [comment]
> I have started a branch tomlm/controlTheme.
> 
> It has applied all of the changes from above but when I run it it blows up loading the assembly looking for styles. I really don't understand the style system, but I think this is a good starting place, as I have created all of the ControlThemes...
> 
> @jinek perhaps you can find this useful?

I don't see the branch:
![image](https://github.com/user-attachments/assets/191a0026-4ba2-4890-a686-f3462235e206)
Not pushed?

**Comment by tomlm** [comment]
doh, yeah. Well. I forgot to push it! 
It should be there now.

**Comment by jinek** [comment]
> doh, yeah. Well. I forgot to push it! It should be there now.

Could you re-check please? I'm not seeing it yet.

**Comment by tomlm** [comment]
This is it [tomlm/controlTheme](https://github.com/jinek/Consolonia/tree/tomlm/controlTheme)

**Comment by jinek** [comment]
on it
