### ISSUE TITLE
Add Rider to .gitignore

### ISSUE THREAD

**Issue by wieslawsoltes** [jinek/Consolonia#14]
![image](https://user-images.githubusercontent.com/2297442/140396638-80808a5b-7cb7-4841-b5d0-1503c3c49ece.png)

**Comment by jinek** [comment]
Those files are asked to add to repo by Rider. Which I doubt to do. Those are personal files, right?

**Comment by wieslawsoltes** [comment]
I think .idea folder should be ignored in `.gitignore`
```
# JetBrains Rider
.idea/
*.sln.iml
``
