### ISSUE TITLE
Visual Designer visual studio doesn't work

### ISSUE THREAD

**Issue by tomlm** [jinek/Consolonia#142]
I was poking around this and made some interesting discoveries.

The way the designer renders the preview window is it has an out of process app which binds to the projects AppBuilder to instantiate the environment and then it renders the control inside of that.  

The problem is that out of process host app is not a console app, and so all console APIs blow up. And even it were a console app it's looking for a bitmap to send back to the preview page.

BUT I managed to get it working sort of by doing this:
1. in program.cs I create an AppBuilder property
2. in UseConsolonia I use **Designer.IsDesignMode** to return a standard Avalonia.Desktop AppBuilder with a #ifdef DEBUG around it
3. I add conditional nuget package references to Avalonia.Desktop environment so they are only included on DEBUG builds
4. I add designer attributes to control
```xaml
             xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
             mc:Ignorable="d" d:DesignWidth="100" d:DesignHeight="100"
```
it displays a preview (although completely illegible)!

Issues I had:
* I had to add FontFamily FontSize Foreground and Background to render anything which didn't have that on it. (The colors panel actually previewed the best because it has explicit colors
* The size of the image that is created is literally 100x100 pixels so I had to zoom to 800% to see anything.

I think this approach *might* work, but I think we need some combination of styling and scaling to make it work.

There are some alternative approaches that might be possible as well, but it would be more complicated
* create an IConsole which paints onto an Avalonia canvas?
* Somehow hack the host process to take snapshot of console window?

I don't know...but I thought I'd record what I figured out for whenever/whomever tries to tackle this.

**Comment by jinek** [comment]
May be we need own plugins for VS and Rider to run a proper out of process terminal and capture the window render. Just first thought.
IConsole which draws to canvas is little hacky but could work. Any mono font would work for it, but we have stuff like special characters, we would need to write own terminal emulator basically.
By the way, theoretically, do we have an option to render some terminal emulator into a bitmap? May be we already have some existing cross-platform emulator which can do this?

**Comment by tomlm** [comment]
Yeah, I'm pursuing that route right now.  I can capture the console output as VT100 codes, as raw char buffer or as a bmp. 

branch tomlm/preview is where I'm working. I'm trying to get a previewer working as Consolonia app, then I will try binding that to via one of the means to the avalonia preview

**Comment by tomlm** [comment]
![image](https://github.com/user-attachments/assets/fe08d5cb-0faf-437d-8e5d-c00eed5cbdbc)
