### ISSUE TITLE
Implement FileDialogs via IStorageProvider implementation  

### ISSUE THREAD

**Issue by tomlm** [jinek/Consolonia#148]

**Comment by jinek** [comment]
Why? Just curious.  Avalonia default dialog will not work for us most probably. Should have some styling/templates probably

**Comment by tomlm** [comment]
Oh. IStoreProvider implements FileOpen and FileSave and PickFolder API.

My new app I want to File/Open and I can't. 

It should be super easy to implement using consolonia itself as a Dialog control.

Don't worry, I'm going to do it because I want it :)

**Comment by tomlm** [comment]
![image](https://github.com/user-attachments/assets/8beecaf4-ee24-4753-9fc3-de563cccf309)
