### ISSUE TITLE
Caret is not drawn by CaretControl

### ISSUE THREAD

**Issue by jinek** [jinek/Consolonia#179]
I'm not sure whether it's intentionally or no, most of the controls contain CaretControl which is supposed to draw caret when the control is focused.
As an example, on the screenshot item "Button" within the grid is currently focused, but there is no caret there:
![image](https://github.com/user-attachments/assets/19db05b0-ea34-4e52-9b6c-cf0f7deb8b87)

**Comment by tomlm** [comment]
what does it mean to draw caret? Is it turn on blinking cursor? Or something else?

**Comment by jinek** [comment]
Yes. Before smth it was blinking over focused element

**Comment by tomlm** [comment]
I can take a look at this.

**Comment by tomlm** [comment]
Hmm...I thought maybe this was something I broke, but the current logic only seems to apply a caret inside of TextBox and it works correctly there.

The current template for CaretControl doesn't seem to ever activate the IsPixel logic. I don't think understand how this works (and how it's supposed to work)
