### ISSUE TITLE
Dialog is broken

### ISSUE THREAD

**Issue by jinek** [jinek/Consolonia#186]
It looks like Dialog background, chrome and title are not painted:
![image](https://github.com/user-attachments/assets/c8e08fb6-cea8-4425-893a-9ceafffd5006)

**Comment by tomlm** [comment]
WHAT THE HECK? This was definitely working yesterday. <Sigh>

**Comment by tomlm** [comment]
Yeah, I went to main and reverted ControlTheme PR and now it looks like this:
![image](https://github.com/user-attachments/assets/4de2f10c-e2cf-4dab-bc1b-4fec4fc264b7)
