### ISSUE TITLE
Startup/exit became slower

### ISSUE THREAD

**Issue by jinek** [jinek/Consolonia#189]
Needs profiling. it seems starting and stopping (especially debuggin) is much more slower.

**Comment by tomlm** [comment]
I enabled a setting on my IDE to load all symbols for all assemblies, is it possible I checked that in?  That definitely slows down loading.

**Comment by jinek** [comment]
> I enabled a setting on my IDE to load all symbols for all assemblies, is it possible I checked that in?  That definitely slows down loading.

I'm using Rider anyway, it does not affect.
I will profile it shortly

**Comment by tomlm** [comment]
This appears to be a linux thing.

When I start the dll directly from CLI in windows
```dotnet Consolonia.Gallery/bin/Debug/net6.0/Consolonia.Gallery.dll```
It starts instantly (<1sec)
When I do the same on ubuntu WSL on windows it takes **8 seconds** just to display the first char.

Something is definitely funky on linux.

**Comment by tomlm** [comment]
This is me. I'm on the fly computing emojii wide char support, and the point when I do that I think is deadlocking the console window.  When I comment out the emojii detection logic it starts fast.

**Comment by jinek** [comment]
Good.
Still does not explain slow stop.

**Comment by tomlm** [comment]
I don't see any delay on exit on ubuntu, both when running from the terminal and when debugging using JetRider.

**Comment by jinek** [comment]
hmmm, I've found that it's issue of the debugger - When I press to stop it directly from Rider, something is going on for several seconds and debugger does not detach. I have to profile Rider itself then

**Comment by tomlm** [comment]
Weird, my rider detaches immediately on Ubuntu
