### ISSUE TITLE
Avalonia.PreviewHost is reserved

### ISSUE THREAD

**Issue by jinek** [jinek/Consolonia#192]
Pushing Avalonia.PreviewHost.11.0.9-alpha-482.nupkg to 'https://www.nuget.org/api/v2/package'...
  PUT https://www.nuget.org/api/v2/package/
  Conflict https://www.nuget.org/api/v2/package/ 409ms
To skip already published packages, use the option --skip-duplicate
error: Response status code does not indicate success: 409 (This package ID has been reserved. Please request access to upload to this reserved namespace from the owner of the reserved prefix, or re-upload the package with a different ID. Go to https://docs.microsoft.com/nuget/reference/id-prefix-reservation learn more about Package ID prefix reservation.).
Usage: dotnet nuget push [arguments] [options]

**Comment by tomlm** [comment]
Yeah, the namespace Avalonia is reserved by the avalonia team. 

I thought I marked this to not pack, I'm surprised it's trying to push it, or were you doing that?

It should be marked as expiremental, may we should move to an experiemental folder?

**Comment by tomlm** [comment]
I don't care what we name it, but I don't think we should publish it yet, if ever.

**Comment by jinek** [comment]
This log is from main branch. I've tried to publish latest commit

**Comment by tomlm** [comment]
oh, you need to merge my Packages PR, I have cleaned all of this up.
