### ISSUE TITLE
Add contribution guide

### ISSUE THREAD

**Issue by vabka** [jinek/Consolonia#39]
Contribution guide should describe how contributors should create their PRs.
It should contain:
- Instruction to prepare development environment
- Definition of ready for PRs
- Link to community (if exists)
- Code style
- Code of conduct
- PR notation
- git commit messages format

**Comment by vabka** [comment]
Some examples of contributions guides:
https://github.com/github/docs/blob/main/CONTRIBUTING.md
https://github.com/AvaloniaUI/Avalonia/blob/master/CONTRIBUTING.md

**Comment by jinek** [comment]
I think should be done after CI/code styling tools setup. Or may be should be in simple version for now.
Because things like code style, formatting, message formatting etc should be checked by CI.
