### ISSUE TITLE
Nuget packaging

### ISSUE THREAD

**Issue by jinek** [jinek/Consolonia#8]
Re-arrange assemblies, setup CI and deployment to NUGET

**Comment by vabka** [comment]
1. Check best practices:
https://docs.microsoft.com/en-us/nuget/create-packages/package-authoring-best-practices
2. Add some properties for nuget package in csproj
https://docs.microsoft.com/en-us/nuget/create-packages/creating-a-package-msbuild
3. Obtain an apikey for nuget: https://docs.microsoft.com/en-us/nuget/nuget-org/scoped-api-keys
4. Setup CI using Azure Pipelines/GH Actions/etc

**Comment by jinek** [comment]
Also a logo needed

**Comment by jinek** [comment]
Basic setup is done. Alpha version is being pushed to official nuget source https://www.nuget.org/packages/Consolonia.Themes.TurboVision/
